<?php
namespace MssPhp\Bitmask;

class SpecialPremium
{
    const VITALPINA = 1;
    const FAMILY_HOTELS_PREMIUM = 2;
    const VINUM_HOTELS_PREMIUM = 4;
    const SÜDTIROL_BALANCE_PREMIUM = 8;
    const VITALPINA_DURCHATMEN = 16;
    const VITALPINA_WOHLFÜHLEN = 32;
    const VITAPLINA_ERNÄHRUNG = 64;
    const VITAPLINA_AKTIV = 128;
    const VITALPINA_PREMIUM = 256;
    const BIKEHOTELS_MOUNTAINBIKE = 512;
    const BIKEHOTELS_BIKE_TOURING_AND_EBIKE = 1024;
    const BIKEHOTELS_ROADBIKE = 2048;
    const BIKEHOTELS_PREMIUM = 4096;
}
