<?php
namespace MssPhp\Bitmask;

class SpecialPremium
{
    const VITALPINA = 1;
    CONST FAMILY_HOTELS_PREMIUM = 2;
    CONST VINUM_HOTELS_PREMIUM = 4;
    CONST SÜDTIROL_BALANCE_PREMIUM = 8;
    CONST VITALPINA_DURCHATMEN = 16;
    CONST VITALPINA_WOHLFÜHLEN = 32;
    CONST VITAPLINA_ERNÄHRUNG = 64;
    CONST VITAPLINA_AKTIV = 128;
    CONST VITALPINA_PREMIUM = 256;
    CONST BIKEHOTELS_MOUNTAINBIKE = 512;
    CONST BIKEHOTELS_BIKE_TOURING_AND_EBIKE = 1024;
    CONST BIKEHOTELS_ROADBIKE = 2048;
    CONST BIKEHOTELS_PREMIUM = 4096;
}
